from flask import Flask, request, render_template, redirect, url_for, flash, send_file
from utils.predict import return_prediction
import csv
import os
from fpdf import FPDF

app = Flask(__name__)
app.secret_key = "super_secret_opticrop_key" 

HISTORY_FILE = 'dataset/prediction_history.csv'

# Initialize CSV file if it doesn't exist
if not os.path.exists(HISTORY_FILE):
    with open(HISTORY_FILE, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['N', 'P', 'K', 'Temperature', 'Humidity', 'pH', 'Rainfall', 'Predicted Crop'])

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/contact')
def contact():
    return render_template('contact.html')

@app.route('/predict', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
        try:
            N = float(request.form['N'])
            P = float(request.form['P'])
            K = float(request.form['K'])
            temp = float(request.form['temperature'])
            humidity = float(request.form['humidity'])
            ph = float(request.form['ph'])
            rainfall = float(request.form['rainfall'])

            result = return_prediction(N, P, K, temp, humidity, ph, rainfall)
            
            if result['success']:
                predicted_crop = result['prediction']
                
                # Save to History
                with open(HISTORY_FILE, mode='a', newline='') as f:
                    writer = csv.writer(f)
                    writer.writerow([N, P, K, temp, humidity, ph, rainfall, predicted_crop])
                
                return render_template('result.html', prediction=predicted_crop)
            else:
                flash(f"Prediction Error: {result.get('error')}", "danger")
                return redirect(url_for('predict'))

        except ValueError:
            flash("Invalid input. Please ensure all fields contain numerical values.", "danger")
            return redirect(url_for('predict'))
        except Exception as e:
            flash(f"An unexpected error occurred: {str(e)}", "danger")
            return redirect(url_for('predict'))

    return render_template('predict.html')

@app.route('/history')
def history():
    records = []
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, mode='r') as f:
            reader = csv.reader(f)
            records = list(reader)[1:] # skip header
    return render_template('history.html', records=records)

@app.route('/download_csv')
def download_csv():
    return send_file(HISTORY_FILE, as_attachment=True)

@app.route('/download_pdf/<crop>')
def download_pdf(crop):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=16, style="B")
    pdf.cell(200, 10, txt="OptiCrop AI - Prediction Report", ln=1, align='C')
    pdf.ln(10)
    pdf.set_font("Helvetica", size=14)
    pdf.cell(200, 10, txt=f"Recommended Crop for Cultivation: {crop.capitalize()}", ln=1, align='L')
    pdf.set_font("Helvetica", size=12)
    pdf.ln(5)
    pdf.multi_cell(0, 10, txt="This recommendation was automatically generated by OptiCrop's predictive engine utilizing a trained Random Forest classifier. The soil composition and environmental metrics provided were cross-referenced against historical yields to identify this optimal crop.")
    
    # Save temporarily to static
    pdf_path = f"static/report_{crop}.pdf"
    pdf.output(pdf_path)
    return send_file(pdf_path, as_attachment=True)

@app.route('/dashboard')
def dashboard():
    import pandas as pd
    df = pd.read_csv('dataset/Crop_recommendation.csv')
    
    # 1. Crop Frequency
    crop_counts = df['label'].value_counts().to_dict()
    
    # 2. Averages per crop (N, P, K, Temp, Hum, Rain)
    # Exclude categorical columns for mean calculation
    numeric_df = df.drop(columns=['label'])
    numeric_df['label'] = df['label']
    grouped = numeric_df.groupby('label').mean().to_dict('index')
    
    return render_template('dashboard.html', crop_counts=crop_counts, grouped=grouped)

@app.errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404

if __name__ == '__main__':
    app.run(debug=True, port=5000)
